import './style.css';
import { stages, nodes, documents, excerpt } from './content.js';
const $=s=>document.querySelector(s);let current=null,results=stages,selected=0,sourceVisible=false;
$('#inventory').textContent=`${nodes.size} RECORDS / ${stages.length} CHAPTERS`;
function button(label,action){const b=document.createElement('button');b.textContent=label;b.onclick=action;return b;}
function message(text){$('#message').textContent=text;}
function navigate(node){history.pushState(null,'',node?'#'+encodeURIComponent(node.key):location.pathname);render(node);}
function showList(list,title){results=list;selected=0;$('#list-title').textContent=title;$('#list').replaceChildren(...list.map((n,i)=>{const b=button('',()=>navigate(n));b.className='index-row'+(i===0?' active':'');const id=document.createElement('span');id.className='number';id.textContent=n.id;const title=document.createElement('span');title.textContent=n.title;const cue=document.createElement('span');cue.className='cue';cue.textContent=n.proposed?'◇':n.children.length?'→':'·';b.append(id,title,cue);return b;}));if(!list.length)$('#list').textContent='  NO MATCHING RECORDS';}
function select(delta){if(!results.length)return;selected=(selected+delta+results.length)%results.length;[...$('#list').children].forEach((b,i)=>b.classList.toggle('active',i===selected));$('#list').children[selected]?.scrollIntoView({block:'nearest'});}
function render(node){current=node;sourceVisible=false;$('#raw').hidden=true;$('#query').value='';$('#view-source').textContent='VIEW SOURCE';$('#view-source').disabled=!node;$('#welcome').hidden=!!node;
 const trail=[];for(let n=node;n;n=n.parent)trail.unshift(n);$('#trail').replaceChildren(button('ROOT',()=>navigate(null)),...trail.map(n=>button('/ '+n.id,()=>navigate(n))));
 $('#record').textContent=node?`RECORD ${node.id} / ${node.proposed?'PROPOSED SUBDIVISION':'FRAMEWORK DOCUMENT'}`:'INVESTING EQUATION / EXPLORER';$('#title').textContent=node?node.title:'Find the signal.';$('#summary').textContent=node?excerpt(node):'A working index of the investment framework. Move through the hierarchy, inspect function contracts, or search directly for a question.';$('#metadata').textContent=node?`SOURCE: ${node.sourcePath}`:'KEYBOARD FIRST. SOURCE DOCUMENTS ALWAYS AVAILABLE.';
 $('#children').replaceChildren(...(node?.children||[]).map(n=>{const b=button('',()=>navigate(n));b.className='child';const id=document.createElement('b');id.textContent=n.id;const name=document.createElement('span');name.textContent=n.title;const cue=document.createElement('small');cue.textContent=n.proposed?'PROPOSED':'OPEN →';b.append(id,name,cue);return b;}));
 showList(node?.children.length?node.children:node?.parent?.children||stages,node?`${node.id} / ${node.children.length?'SECTIONS':'NEIGHBORS'}`:'ROOT / CHAPTERS');message(node?`OPEN / ${node.id} — ${node.title}`:'READY / Choose a chapter or start typing.');
}
function toggleSource(){if(!current){message('SELECT A RECORD FIRST');return;}sourceVisible=!sourceVisible;$('#raw').hidden=!sourceVisible;$('#raw').textContent=documents[current.sourcePath];$('#view-source').textContent=sourceVisible?'HIDE SOURCE':'VIEW SOURCE';if(sourceVisible)$('#raw').scrollIntoView({block:'nearest'});message(sourceVisible?'SOURCE / Original Markdown':'RECORD / Summary view');}
$('#view-source').onclick=toggleSource;$('#root').onclick=()=>navigate(null);
$('#query').addEventListener('input',()=>{const q=$('#query').value.trim().toLowerCase();if(!q){showList(current?.children.length?current.children:stages,'INDEX');return;}const list=[...nodes.values()].filter(n=>(n.id+' '+n.title).toLowerCase().includes(q));showList(list,`SEARCH / ${list.length} MATCHES`);message('SEARCH / Enter opens the selected match.');});
$('#command').addEventListener('submit',e=>{e.preventDefault();const q=$('#query').value.trim();if(/^home$/i.test(q))navigate(null);else if(/^back$/i.test(q))navigate(current?.parent||null);else if(/^source$/i.test(q))toggleSource();else if(/^help$/i.test(q))message('COMMANDS / home · back · open <ID> · source · help. Or search by title.');else if(/^open\s+/i.test(q)){const id=q.replace(/^open\s+/i,'').toUpperCase();const matches=[...nodes.values()].filter(n=>n.id===id);if(matches.length===1)navigate(matches[0]);else{showList(matches,`ID / ${id}`);message(matches.length?'MULTIPLE MATCHES / Select a record':'NO RECORD WITH ID '+id);}}else if(results[selected])navigate(results[selected]);else message('NO MATCH / Try a section ID such as 2C.');});
window.addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){if(e.target!==document.body&&e.target!==$('#query')&&!e.target.closest('.index-panel'))return;e.preventDefault();select(e.key==='ArrowDown'?1:-1);}else if(e.key==='/'&&e.target!==$('#query')){e.preventDefault();$('#query').focus();}else if(e.key==='Enter'&&e.target===document.body&&results[selected])navigate(results[selected]);else if(e.key==='Escape'){if($('#query').value){$('#query').value='';render(current);}else navigate(current?.parent||null);}});
function fromURL(){let key='';try{key=decodeURIComponent(location.hash.slice(1));}catch{}render(nodes.get(key)||null);}window.addEventListener('popstate',fromURL);fromURL();
if(import.meta.env.PROD){$('.home').href='#';$('.home').textContent='[←] ROOT';$('.home').onclick=()=>navigate(null);}
